language: python
python:
  - 3.5

before_script:
  - sudo apt-get install -y gpac
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install: pip install -r requirements.txt

script: pytest -v --cov=myclips --cov-report=xml

after_script:
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
